import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Onest } from "next/font/google";
import localFont from "next/font/local";
import { cn } from "~/lib/utils";
import "./globals.css";

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(onest.variable, geistMono.variable, "font-sans flex min-h-dvh flex-col")}>
        {children}
      </body>
    </html>
  );
}
